[build-system]
requires = ["maturin>=0.15,<0.16"]
build-backend = "maturin"

[project]
name = "pyo3-mixed-submodule"
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Rust"
]

[tool.maturin]
module-name = "pyo3_mixed_submodule.rust_module.rust"
