env:
  RUST_BACKTRACE: 1

build_and_test: &BUILD_AND_TEST
  setup_script:
    - curl https://sh.rustup.rs -sSf --output rustup.sh
    - sh rustup.sh -y --default-toolchain stable
    - python3 -m pip install --upgrade cffi virtualenv
  build_script:
    - cargo build
  test_script:
    - cargo test

freebsd_task:
  name: Test (x86_64 FreeBSD)
  freebsd_instance:
    image_family: freebsd-12-2
  env:
    PATH: $HOME/.cargo/bin:$PATH
  registry_cache:
    folder: $HOME/.cargo/registry
    fingerprint_script:
      - echo $CIRRUS_OS
      - cat Cargo.lock
  target_cache:
    folder: target
    fingerprint_script:
      - echo $CIRRUS_OS
      - cat Cargo.lock
  install_script:
    - pkg install -y curl bash python
    - python3 -m ensurepip
  <<: *BUILD_AND_TEST

macos_arm64_task:
  name: Test (arm64 macOS)
  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-xcode
  env:
    PATH: $HOME/.cargo/bin:/opt/homebrew/opt/python@3.10/bin:$PATH
  registry_cache:
    folder: $HOME/.cargo/registry
    fingerprint_script:
      - echo $CIRRUS_OS
      - cat Cargo.lock
  target_cache:
    folder: target
    fingerprint_script:
      - echo $CIRRUS_OS
      - cat Cargo.lock
  install_script:
    - brew install python3
  <<: *BUILD_AND_TEST

linux_aarch64_task:
  name: Test (arm64 Linux)
  compute_engine_instance:
    image_project: cirrus-images
    image: family/docker-builder-arm64
    architecture: arm64
    platform: linux
    cpu: 4
    memory: 4G
  env:
    PATH: /root/.cargo/bin:$PATH
  registry_cache:
    folder: /root/.cargo/registry
    fingerprint_script:
      - echo $CIRRUS_OS
      - cat Cargo.lock
  target_cache:
    folder: target
    fingerprint_script:
      - echo $CIRRUS_OS
      - cat Cargo.lock
  install_script:
    - apt-get update
    - apt-get install -y python3-dev python3-pip python-is-python3
  <<: *BUILD_AND_TEST