env:
  RUST_BACKTRACE: 1

build_and_test: &BUILD_AND_TEST
  # only run tasks on pull request or bors related branches
  only_if: $CIRRUS_BRANCH == 'staging' || $CIRRUS_BRANCH == 'trying' || $CIRRUS_PR != ""
  setup_script:
    - curl https://sh.rustup.rs -sSf --output rustup.sh
    - sh rustup.sh -y --default-toolchain stable
    - rustup target add wasm32-wasi
    - python3 -m pip install --upgrade cffi virtualenv
  build_script:
    - cargo build
  test_script:
    - cargo test

freebsd_task:
  name: Test (x86_64 FreeBSD)
  freebsd_instance:
    image_family: freebsd-13-1
  env:
    PATH: $HOME/.cargo/bin:$PATH
  registry_cache:
    folder: $HOME/.cargo/registry
    fingerprint_script:
      - echo $CIRRUS_OS
      - cat Cargo.lock
  target_cache:
    folder: target
    fingerprint_script:
      - echo $CIRRUS_OS
      - cat Cargo.lock
  install_script:
    - pkg install -y curl bash python
    - python3 -m ensurepip
  <<: *BUILD_AND_TEST

macos_arm64_task:
  name: Test (arm64 macOS)
  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-xcode
  env:
    PATH: $HOME/.cargo/bin:/opt/homebrew/opt/python@3.10/bin:$PATH
  registry_cache:
    folder: $HOME/.cargo/registry
    fingerprint_script:
      - echo $CIRRUS_OS
      - cat Cargo.lock
  target_cache:
    folder: target
    fingerprint_script:
      - echo $CIRRUS_OS
      - cat Cargo.lock
  install_script:
    - brew install python3
    - python3 -m pip install uniffi-bindgen==0.23.0
  <<: *BUILD_AND_TEST

linux_aarch64_task:
  name: Test (arm64 Linux)
  arm_container:
    image: python:3.11
    cpu: 4
    memory: 4G
  env:
    PATH: /root/.cargo/bin:$PATH
  registry_cache:
    folder: /root/.cargo/registry
    fingerprint_script:
      - echo $CIRRUS_OS
      - cat Cargo.lock
  target_cache:
    folder: target
    fingerprint_script:
      - echo $CIRRUS_OS
      - cat Cargo.lock
  install_script:
    - python3 -m pip install uniffi-bindgen==0.23.0
  <<: *BUILD_AND_TEST