env:
  RUST_BACKTRACE: 1
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

build_and_test:
  &BUILD_AND_TEST # only run tasks on pull request or github merge queue branches
  only_if: $CIRRUS_BRANCH =~ 'gh-readonly-queue/.*' || $CIRRUS_PR != ""
  setup_script:
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
    - rustup target add wasm32-wasip1
    - python3 -m pip install --upgrade cffi virtualenv
  build_script:
    - cargo build
  test_script:
    - cargo test

freebsd_task:
  name: Test (x86_64 FreeBSD)
  freebsd_instance:
    image_family: freebsd-14-3
  env:
    PATH: $HOME/.cargo/bin:$PATH
  target_cache:
    folder: target
    fingerprint_script:
      - echo $CIRRUS_OS
      - cat Cargo.lock
  install_script:
    - pkg install -y bash git python
    - python3 -m ensurepip
  <<: *BUILD_AND_TEST
