#!/usr/bin/env python3

import importlib.resources

import pyo3_mixed_include_exclude

assert pyo3_mixed_include_exclude.get_42() == 42

# Verify that the file generated by build.rs and included from OUT_DIR is present
ref = importlib.resources.files("pyo3_mixed_include_exclude").joinpath("generated_info.txt")
assert ref.read_text() == "hello from build.rs", f"Unexpected content: {ref.read_text()!r}"

print("SUCCESS")
