[package]
name = "pyo3-mixed"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "pyo3-bin"    # keep the name with a dash to test `.pdb` file name
path = "src/main.rs"
