[package]
authors = ["konstin <konstin@mailbox.org>"]
name = "pyo3-mixed"
version = "2.1.3"
description = "Implements a dummy function combining rust and python"
readme = "Readme.md"
edition = "2018"

[dependencies]
pyo3 = { version = "0.15.1", features = ["extension-module"] }

[lib]
name = "pyo3_mixed"
crate-type = ["cdylib"]
