[package]
name = "uniffi-pure"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "uniffi_pure"
crate-type = ["cdylib"]

[dependencies]
uniffi = "0.24.1"

[build-dependencies]
uniffi = { version = "0.24.1", features = ["build"] }
