name: 🐛 Bug Report
description: Create a bug report
type: Bug
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report!
        Please fill out the form below...
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Please provide a clear and concise description of what the bug is.
      placeholder: The bug is...
    validations:
      required: true
  - type: input
    id: maturin_version
    attributes:
      label: Your maturin version (`maturin --version`)
      placeholder: ex. 0.14.1
    validations:
      required: true
  - type: input
    id: py_version
    attributes:
      label: Your Python version (`python -V`)
      placeholder: ex. Python 3.10.0
    validations:
      required: true
  - type: input
    id: pip_version
    attributes:
      label: Your pip version (`pip -V`)
      placeholder: ex. pip 21.1.3
    validations:
      required: true
  - type: dropdown
    id: bindings
    attributes:
      label: What bindings you're using
      options:
        - "pyo3"
        - "cffi"
        - "uniffi"
        - "bin"
    validations:
      required: false
  - type: checkboxes
    id: cargo-build
    attributes:
      label: Does `cargo build` work?
      options:
        - label: Yes, it works
          required: false
  - type: checkboxes
    id: windows-unix-path
    attributes:
      label: If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?
      options:
        - label: "Yes"
          required: false
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Please list the exact steps required to reproduce your error with all command output and if possible with a repository. Please run maturin with `RUST_LOG=maturin=debug` being set, e.g. `RUST_LOG=maturin=debug maturin build` and share the output, either in a codeblock or as a [gist](https://gist.github.com/)
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true
