#!/usr/bin/env python3

import importlib.resources

import cffi_mixed_include_exclude

point = cffi_mixed_include_exclude.lib.get_origin()
assert cffi_mixed_include_exclude.lib.is_in_range(point, 0.0)

# Verify that the file generated by build.rs and included from OUT_DIR is present
ref = importlib.resources.files("cffi_mixed_include_exclude").joinpath("generated_info.txt")
assert ref.read_text() == "hello from build.rs", f"Unexpected content: {ref.read_text()!r}"

print("SUCCESS")
