name: Docker test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  docker-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Build Docker container
        run: |
          docker pull konstin2/maturin:main
          docker build --cache-from konstin2/maturin:main -t maturin .
      - name: Test the Docker container
        run: ./test-dockerfile.sh
